### PR TITLE
XSLT EXERCISE 2 and the Source XML for the CDV course

### PR DESCRIPTION
**Pull request by RJP43**
@ebeshero 

The solution for this file is in the Solutions To Post folder in the upgMentors DropBox. This assignment was created based off of CDA XSLT Exercise 4. 

To come: CDV Exercise 3 based off of CDA Exercise 5 and 6

### CODE REVIEW

**Comment by ebeshero** [comment]
Thanks, @RJP43! If it's the same assignment in both, I think I'll remove the assignment numbering from the file names so we don't have to keep track of editing it in two different places...

**Comment by RJP43** [comment]
It is not exactly the same ... this new version has a lot of detail pulled from CDA 2 and 3 about concepts that would be repetitive if kept in the CDA 4. However there are parts that I edited that were unclear in the original that should probably get transferred over. And the source document in the end can be the last one I uploaded with the _CDV ending once I make the adjustments in CDA 4 to match the changes.

**Comment by ebeshero** [comment]
Okay-- sounds like we'd better produce **both** versions together while we're thinking about it...Thank you, Becca! @RJP43

**Comment by RJP43** [comment]
* _CDV ending 
*changes

This won't take long at all!

**Comment by RJP43** [comment]
besides the two exercises have to stay marked separately because XSLTExercise2_CDV corresponds with  the [CDA XSLTExercise4](http://newtfire.org/dh/XSLTExercise4.html) so you couldn't remove the CDV or you would have two completely different XSLTExercise2 (one being the [XSLTExercise2 for the CDA course](http://newtfire.org/dh/XSLTExercise2.html)). However the couple of edits to CDA XSLTExercise4 will be an easy edit. We can remove the _CDV ending to the source XML because both CDA XSLTExercise4 and XSLTExercise2_CDV will use that [single document](https://github.com/ebeshero/newtFire-webDev/blob/master/cdv-course/NelsonArticle_1888-07-30_CDV.xml) (as in the last one I committed with the edits in the `<toneElements>` list at the start of the XML which will need moved into the common folder) once I make those edits to CDA XSLTExercise4. 

As for XSLTExercise3_CDV I am working on that and will push my draft (which combines CDA [XSLTExercise5](http://newtfire.org/dh/XSLTExercise5.html) and [XSLTExercise6](http://newtfire.org/dh/XSLTExercise6.html)) after class today.

**Comment by RJP43** [comment]
and your welcome @ebeshero :)

**Pull request merged**
