### PR TITLE
update to Becca's author header to include twitter handle

### PR DESCRIPTION
**Pull request by RJP43**
@ebeshero Here are the minor edits to the two author headers where I am mentioned. I am fine leaving my Pitt email for contact and I simply added my twitter handle after it. Be great if you could get this live whenever you get a chance. 

Pilar will be learning about git and github on Thursday and I encouraged her to boast about my git tutorial ... so be great if people could shout me out.

### CODE REVIEW

**Comment by ebeshero** [comment]
@RJP43 I've posted the updates! See how it looks at http://newtfire.org/dh/explainGitShell.html (and the others)

**Comment by RJP43** [comment]
@ebeshero Fantastic! Thank you!

**Comment by RJP43** [comment]
@ebeshero Looks a little weird on [this one](http://newtfire.org/dh/SchematronExercise1.html) I think just because the author line is so long with Brooke's, Nicole's, and my info. Perhaps a line break after the author line to jump your editor line down so it fits all on the second line would look better. Thoughts?

**Comment by ebeshero** [comment]
@RJP43 Yeah, I could try that line break... (As usual, my wide screen means I see more on a line than probably most visitors would.)

**Comment by RJP43** [comment]
Ahh ok. Alright lets try this: https://github.com/ebeshero/newtFire-webDev/pull/92

**Comment by ebeshero** [comment]
@RJP43 Take a look at the page on the web again...I made one more change b/c the author info was running into the dh | ds logo at the top.

**Comment by RJP43** [comment]
@ebeshero Ahh yes. Much better! Thanks again!

**Pull request merged**
